# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Vivado/TinyCPU_newarch/src/TinyCPU.cache/wt [current_project]
set_property parent.project_path E:/Vivado/TinyCPU_newarch/src/TinyCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Vivado/TinyCPU_newarch/src/TinyCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/sources_1/new/utility.v
  E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/sources_1/new/display.v
  E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/sources_1/new/Serial.v
  E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/sources_1/new/RegSet.v
  E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/sources_1/new/MainMemory.v
  E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/sources_1/new/Decoder.v
  E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/sources_1/new/Controller.v
  E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/sources_1/new/Clock.v
  E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/sources_1/new/ALU.v
  E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/sources_1/new/AddressTranslator.v
  E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/sources_1/new/CPU.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/constrs_1/new/TinyCPU_xdc.xdc
set_property used_in_implementation false [get_files E:/Vivado/TinyCPU_newarch/src/TinyCPU.srcs/constrs_1/new/TinyCPU_xdc.xdc]


synth_design -top CPU -part xc7a35tcsg324-1


write_checkpoint -force -noxdef CPU.dcp

catch { report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb }
